server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DEMO
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat.max-active: 20
    tomcat.max-idle: 8
    tomcat.min-idle: 8
    tomcat.initial-size: 10

  thymeleaf:
    cache: false

  jpa:
    database: MYSQL
    show-sql: true
    hibernate.ddl-auto: update
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
